name = "jwfsim"
uuid = "5b426cd4-9a00-43b7-822b-db0a8b903e22"
authors = ["jjgomezcadenas <jjgomezcadenas@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
